# constants.py


import pygame


WIDTH = 1700
HEIGHT = 760
FPS = 120

TABLE_MARGIN_X = 70
TABLE_MARGIN_TOP = 90
TABLE_MARGIN_BOTTOM = 140
RAIL_THICKNESS_PX = 28

TABLE_WIDTH_MM = 3657.6
TABLE_HEIGHT_MM = 1828.8
BALL_DIAMETER_MM = 68.0
BALL_RADIUS_MM = BALL_DIAMETER_MM / 2
CORNER_POCKET_DIAMETER_MM = 100.0
CORNER_POCKET_RADIUS_MM = CORNER_POCKET_DIAMETER_MM / 2
CORNER_POCKET_WIDTH_MM = 73.0
CORNER_POCKET_DEPTH_MM = 15.0
SIDE_POCKET_WIDTH_MM = 90.0
SIDE_POCKET_DEPTH_MM = 0.0

TABLE_SCALE = min(
    (WIDTH - TABLE_MARGIN_X * 2) / TABLE_WIDTH_MM,
    (HEIGHT - TABLE_MARGIN_TOP - TABLE_MARGIN_BOTTOM) / TABLE_HEIGHT_MM,
)
TABLE_PIXEL_WIDTH = int(round(TABLE_WIDTH_MM * TABLE_SCALE))
TABLE_PIXEL_HEIGHT = int(round(TABLE_HEIGHT_MM * TABLE_SCALE))
TABLE_RECT = pygame.Rect(
    (WIDTH - TABLE_PIXEL_WIDTH) // 2,
    TABLE_MARGIN_TOP,
    TABLE_PIXEL_WIDTH,
    TABLE_PIXEL_HEIGHT,
)

BALL_RADIUS = max(1, int(round(BALL_RADIUS_MM * TABLE_SCALE)))

FRICTION = 320.0
MIN_SPEED = 14.0
WALL_BOUNCE = 0.9
BALL_COLLISION_DAMP = 0.97
MAX_SHOT_SPEED = 3100.0
MIN_SHOT_SPEED = 90.0
MAX_PULL_DISTANCE = 420.0
GUIDE_LENGTH = 360.0
MAX_FOULS = 3
CHARGE_RATE = MAX_SHOT_SPEED  # mm/s gain while holding charge key

PHASE_AIM = "aim"
PHASE_MOVING = "moving"
PHASE_ROUND_OVER = "round_over"

BG_COLOR = (76, 52, 35)
TABLE_COLOR = (20, 120, 20)
RAIL_COLOR = (36, 86, 36)
BALL_COLOR = (245, 245, 245)
BLACK_BALL_COLOR = (28, 28, 28)
POCKET_COLOR = (18, 18, 18)
AIM_COLOR = (255, 232, 128)
BAR_BG = (30, 30, 30)
BAR_FILL = (255, 200, 40)
TEXT_COLOR = (245, 245, 245)
OVERLAY_COLOR = (0, 0, 0, 150)

BLACK_START_POS = pygame.Vector2(TABLE_WIDTH_MM * 0.25, TABLE_HEIGHT_MM * 0.5)
PYRAMID_APEX_POS = pygame.Vector2(TABLE_WIDTH_MM * 0.75, TABLE_HEIGHT_MM * 0.5)
